/*

Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair(arri, arrj) from the array such that i != j.
Input Format

The first line contains size of array.
Second line contains the elements of the array.
Constraints

1 <= N <= 10^5
1 <= arr[i] <= 10^5
Output Format

Output the required integer.
Sample Input 0

4
4 8 12 16
Sample Output 0

8

  */

import java.io.*;
import java.util.*;

public class Solution {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int[] arr = new int[n];
        for(int i=0; i<n; i++)
        {
            arr[i] = sc.nextInt();
        }
        int max = Integer.MIN_VALUE;
        for(int i=0; i<n-1; i++)
        {
        for(int j=i+1; j<n; j++)
        {
            int and = arr[i]&arr[j];
            if(and>max) max=and;
            else continue;
        }
        }
        System.out.print(max);
    }
}
